### PR TITLE
Upgrade forked rrweb to newest version

### PR DESCRIPTION
**Pull request by skitterm**
Upgrades this fork to use the newest version of rrweb (`2.0.0-alpha.17`). Was at `2.0.0-alpha.7`

### CODE REVIEW

**Comment by skitterm** [comment]
@tmeasday looks like I'm not authorized to merge this pull request. Can I get merge privileges on this repo?

**Review by andrewortwein — COMMENTED** [review]
Is it safe to assume that this is fine to upgrade without any tests, since we aren't actively using it anywhere?

**Comment by tmeasday** [comment]
I added `@chromaui/engineering` @skitterm.

Re: this PR -- would it make sense just to reset `main` of this repo to the version in question on the other repo? I'm not sure we still need the other modifications on this fork.

**Comment by skitterm** [comment]
> Re: this PR -- would it make sense just to reset main of this repo to the version in question on the other repo? I'm not sure we still need the other modifications on this fork.

@tmeasday good point, I'll give that a go.

**Comment by skitterm** [comment]
@tmeasday actually, after looking through the commits and [contributors](https://github.com/chromaui/rrweb/graphs/contributors) of the fork, none of us are in there, which gives me the confidence to say that we can just upgrade from upstream instead of having to reset.

**Comment by skitterm** [comment]
> Is it safe to assume that this is fine to upgrade without any tests, since we aren't actively using it anywhere?

@andrewortwein yes! I'll do a PR to the e2e repo which will use our existing tests to make sure we don't regress.

**Review by andrewortwein — APPROVED** [review]
🆙🍴👍🏻

**Pull request merged**
